import { Megaphone } from "lucide-react";
import AcceleratorPageTemplate, { AcceleratorConfig } from "@/components/accelerators/AcceleratorPageTemplate";

const marketingConfig: AcceleratorConfig = {
  id: "marketing",
  name: "Marketing",
  tagline: "Streamline Campaigns & Maximize Impact",
  description: "Transform your marketing operations with automated workflows for campaign planning, content creation, social media management, and performance analytics. Drive results with data-driven insights.",
  icon: Megaphone,
  gradientFrom: "from-pink-500",
  gradientTo: "to-rose-500",
  workflows: [
    {
      id: "MKT-PAC-001",
      name: "Campaign Planning & Analysis",
      description: "Comprehensive workflow for planning, executing, and analyzing marketing campaigns with real-time metrics tracking."
    },
    {
      id: "MKT-GCP-002",
      name: "Social Media Calendar Management",
      description: "Centralized management of publication schedules across all social media platforms with approval workflows."
    },
    {
      id: "MKT-CAM-003",
      name: "Promotional Materials Creation & Approval",
      description: "Streamlined process for creating, reviewing, and approving promotional content with stakeholder collaboration."
    },
    {
      id: "MKT-AMA-004",
      name: "Campaign Metrics Analysis",
      description: "Automated collection and analysis of campaign performance data with customizable dashboards and reports."
    },
    {
      id: "MKT-SLG-005",
      name: "Campaign Lead Tracking",
      description: "End-to-end tracking of leads generated by marketing campaigns with attribution and scoring."
    },
    {
      id: "MKT-GPM-006",
      name: "Marketing Budget Management",
      description: "Complete budget planning, allocation, and tracking across all marketing initiatives and channels."
    },
    {
      id: "MKT-AFL-007",
      name: "Product Launch Workflow Automation",
      description: "Automated workflows for coordinating all aspects of product launches from planning to execution."
    },
    {
      id: "MKT-CES-008",
      name: "Creative & Strategy Team Collaboration",
      description: "Seamless collaboration between creative teams and strategists with integrated feedback loops."
    },
    {
      id: "MKT-AEC-009",
      name: "Content Strategy Approval",
      description: "Structured approval process for content strategies with multi-level review and sign-off capabilities."
    },
  ],
  benefits: [
    "Reduce campaign planning time by 60%",
    "Centralize all marketing assets",
    "Automate approval workflows",
    "Real-time performance tracking",
    "Improve team collaboration",
    "Standardize content processes",
    "Integrate with existing tools",
    "Scale marketing operations"
  ],
  stats: [
    { value: "60%", label: "Faster Campaigns" },
    { value: "9", label: "Workflows" },
    { value: "100+", label: "Automations" }
  ],
  nextAccelerator: { name: "Sales", href: "/accelerators/sales" }
};

export default function MarketingAccelerator() {
  return <AcceleratorPageTemplate config={marketingConfig} />;
}
