/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AcceleratorsIndexRouteImport } from './routes/accelerators/index'
import { Route as AcceleratorsCustomerServiceRouteImport } from './routes/accelerators/customer-service'
import { Route as AcceleratorsFinanceRouteImport } from './routes/accelerators/finance'
import { Route as AcceleratorsHrRouteImport } from './routes/accelerators/hr'
import { Route as AcceleratorsItRouteImport } from './routes/accelerators/it'
import { Route as AcceleratorsMarketingRouteImport } from './routes/accelerators/marketing'
import { Route as AcceleratorsOperationsRouteImport } from './routes/accelerators/operations'
import { Route as AcceleratorsRdRouteImport } from './routes/accelerators/rd'
import { Route as AcceleratorsSalesRouteImport } from './routes/accelerators/sales'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter/confirm'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter/unsubscribe'
import { Route as ServicesAtlassianRouteImport } from './routes/services/atlassian'
import { Route as ServicesCloudMigrationRouteImport } from './routes/services/cloud-migration'
import { Route as ServicesCustomDevelopmentRouteImport } from './routes/services/custom-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsIndexRoute = AcceleratorsIndexRouteImport.update({
  id: '/accelerators/',
  path: '/accelerators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsCustomerServiceRoute =
  AcceleratorsCustomerServiceRouteImport.update({
    id: '/accelerators/customer-service',
    path: '/accelerators/customer-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcceleratorsFinanceRoute = AcceleratorsFinanceRouteImport.update({
  id: '/accelerators/finance',
  path: '/accelerators/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsHrRoute = AcceleratorsHrRouteImport.update({
  id: '/accelerators/hr',
  path: '/accelerators/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsItRoute = AcceleratorsItRouteImport.update({
  id: '/accelerators/it',
  path: '/accelerators/it',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsMarketingRoute = AcceleratorsMarketingRouteImport.update({
  id: '/accelerators/marketing',
  path: '/accelerators/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsOperationsRoute = AcceleratorsOperationsRouteImport.update({
  id: '/accelerators/operations',
  path: '/accelerators/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsRdRoute = AcceleratorsRdRouteImport.update({
  id: '/accelerators/rd',
  path: '/accelerators/rd',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorsSalesRoute = AcceleratorsSalesRouteImport.update({
  id: '/accelerators/sales',
  path: '/accelerators/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAtlassianRoute = ServicesAtlassianRouteImport.update({
  id: '/services/atlassian',
  path: '/services/atlassian',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudMigrationRoute = ServicesCloudMigrationRouteImport.update({
  id: '/services/cloud-migration',
  path: '/services/cloud-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomDevelopmentRoute =
  ServicesCustomDevelopmentRouteImport.update({
    id: '/services/custom-development',
    path: '/services/custom-development',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/accelerators/customer-service': typeof AcceleratorsCustomerServiceRoute
  '/accelerators/finance': typeof AcceleratorsFinanceRoute
  '/accelerators/hr': typeof AcceleratorsHrRoute
  '/accelerators/it': typeof AcceleratorsItRoute
  '/accelerators/marketing': typeof AcceleratorsMarketingRoute
  '/accelerators/operations': typeof AcceleratorsOperationsRoute
  '/accelerators/rd': typeof AcceleratorsRdRoute
  '/accelerators/sales': typeof AcceleratorsSalesRoute
  '/blog/$id': typeof BlogIdRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/atlassian': typeof ServicesAtlassianRoute
  '/services/cloud-migration': typeof ServicesCloudMigrationRoute
  '/services/custom-development': typeof ServicesCustomDevelopmentRoute
  '/accelerators/': typeof AcceleratorsIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/accelerators/customer-service': typeof AcceleratorsCustomerServiceRoute
  '/accelerators/finance': typeof AcceleratorsFinanceRoute
  '/accelerators/hr': typeof AcceleratorsHrRoute
  '/accelerators/it': typeof AcceleratorsItRoute
  '/accelerators/marketing': typeof AcceleratorsMarketingRoute
  '/accelerators/operations': typeof AcceleratorsOperationsRoute
  '/accelerators/rd': typeof AcceleratorsRdRoute
  '/accelerators/sales': typeof AcceleratorsSalesRoute
  '/blog/$id': typeof BlogIdRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/atlassian': typeof ServicesAtlassianRoute
  '/services/cloud-migration': typeof ServicesCloudMigrationRoute
  '/services/custom-development': typeof ServicesCustomDevelopmentRoute
  '/accelerators': typeof AcceleratorsIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/accelerators/customer-service': typeof AcceleratorsCustomerServiceRoute
  '/accelerators/finance': typeof AcceleratorsFinanceRoute
  '/accelerators/hr': typeof AcceleratorsHrRoute
  '/accelerators/it': typeof AcceleratorsItRoute
  '/accelerators/marketing': typeof AcceleratorsMarketingRoute
  '/accelerators/operations': typeof AcceleratorsOperationsRoute
  '/accelerators/rd': typeof AcceleratorsRdRoute
  '/accelerators/sales': typeof AcceleratorsSalesRoute
  '/blog/$id': typeof BlogIdRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/services/atlassian': typeof ServicesAtlassianRoute
  '/services/cloud-migration': typeof ServicesCloudMigrationRoute
  '/services/custom-development': typeof ServicesCustomDevelopmentRoute
  '/accelerators/': typeof AcceleratorsIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/accelerators/customer-service'
    | '/accelerators/finance'
    | '/accelerators/hr'
    | '/accelerators/it'
    | '/accelerators/marketing'
    | '/accelerators/operations'
    | '/accelerators/rd'
    | '/accelerators/sales'
    | '/blog/$id'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/newsletter/confirm'
    | '/newsletter/unsubscribe'
    | '/services/atlassian'
    | '/services/cloud-migration'
    | '/services/custom-development'
    | '/accelerators/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/accelerators/customer-service'
    | '/accelerators/finance'
    | '/accelerators/hr'
    | '/accelerators/it'
    | '/accelerators/marketing'
    | '/accelerators/operations'
    | '/accelerators/rd'
    | '/accelerators/sales'
    | '/blog/$id'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/newsletter/confirm'
    | '/newsletter/unsubscribe'
    | '/services/atlassian'
    | '/services/cloud-migration'
    | '/services/custom-development'
    | '/accelerators'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/partners'
    | '/accelerators/customer-service'
    | '/accelerators/finance'
    | '/accelerators/hr'
    | '/accelerators/it'
    | '/accelerators/marketing'
    | '/accelerators/operations'
    | '/accelerators/rd'
    | '/accelerators/sales'
    | '/blog/$id'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/newsletter/confirm'
    | '/newsletter/unsubscribe'
    | '/services/atlassian'
    | '/services/cloud-migration'
    | '/services/custom-development'
    | '/accelerators/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  AcceleratorsCustomerServiceRoute: typeof AcceleratorsCustomerServiceRoute
  AcceleratorsFinanceRoute: typeof AcceleratorsFinanceRoute
  AcceleratorsHrRoute: typeof AcceleratorsHrRoute
  AcceleratorsItRoute: typeof AcceleratorsItRoute
  AcceleratorsMarketingRoute: typeof AcceleratorsMarketingRoute
  AcceleratorsOperationsRoute: typeof AcceleratorsOperationsRoute
  AcceleratorsRdRoute: typeof AcceleratorsRdRoute
  AcceleratorsSalesRoute: typeof AcceleratorsSalesRoute
  BlogIdRoute: typeof BlogIdRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRoute
  ServicesAtlassianRoute: typeof ServicesAtlassianRoute
  ServicesCloudMigrationRoute: typeof ServicesCloudMigrationRoute
  ServicesCustomDevelopmentRoute: typeof ServicesCustomDevelopmentRoute
  AcceleratorsIndexRoute: typeof AcceleratorsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/': {
      id: '/accelerators/'
      path: '/accelerators'
      fullPath: '/accelerators/'
      preLoaderRoute: typeof AcceleratorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/customer-service': {
      id: '/accelerators/customer-service'
      path: '/accelerators/customer-service'
      fullPath: '/accelerators/customer-service'
      preLoaderRoute: typeof AcceleratorsCustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/finance': {
      id: '/accelerators/finance'
      path: '/accelerators/finance'
      fullPath: '/accelerators/finance'
      preLoaderRoute: typeof AcceleratorsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/hr': {
      id: '/accelerators/hr'
      path: '/accelerators/hr'
      fullPath: '/accelerators/hr'
      preLoaderRoute: typeof AcceleratorsHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/it': {
      id: '/accelerators/it'
      path: '/accelerators/it'
      fullPath: '/accelerators/it'
      preLoaderRoute: typeof AcceleratorsItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/marketing': {
      id: '/accelerators/marketing'
      path: '/accelerators/marketing'
      fullPath: '/accelerators/marketing'
      preLoaderRoute: typeof AcceleratorsMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/operations': {
      id: '/accelerators/operations'
      path: '/accelerators/operations'
      fullPath: '/accelerators/operations'
      preLoaderRoute: typeof AcceleratorsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/rd': {
      id: '/accelerators/rd'
      path: '/accelerators/rd'
      fullPath: '/accelerators/rd'
      preLoaderRoute: typeof AcceleratorsRdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerators/sales': {
      id: '/accelerators/sales'
      path: '/accelerators/sales'
      fullPath: '/accelerators/sales'
      preLoaderRoute: typeof AcceleratorsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/atlassian': {
      id: '/services/atlassian'
      path: '/services/atlassian'
      fullPath: '/services/atlassian'
      preLoaderRoute: typeof ServicesAtlassianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-migration': {
      id: '/services/cloud-migration'
      path: '/services/cloud-migration'
      fullPath: '/services/cloud-migration'
      preLoaderRoute: typeof ServicesCloudMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-development': {
      id: '/services/custom-development'
      path: '/services/custom-development'
      fullPath: '/services/custom-development'
      preLoaderRoute: typeof ServicesCustomDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  AcceleratorsCustomerServiceRoute: AcceleratorsCustomerServiceRoute,
  AcceleratorsFinanceRoute: AcceleratorsFinanceRoute,
  AcceleratorsHrRoute: AcceleratorsHrRoute,
  AcceleratorsItRoute: AcceleratorsItRoute,
  AcceleratorsMarketingRoute: AcceleratorsMarketingRoute,
  AcceleratorsOperationsRoute: AcceleratorsOperationsRoute,
  AcceleratorsRdRoute: AcceleratorsRdRoute,
  AcceleratorsSalesRoute: AcceleratorsSalesRoute,
  BlogIdRoute: BlogIdRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRoute,
  ServicesAtlassianRoute: ServicesAtlassianRoute,
  ServicesCloudMigrationRoute: ServicesCloudMigrationRoute,
  ServicesCustomDevelopmentRoute: ServicesCustomDevelopmentRoute,
  AcceleratorsIndexRoute: AcceleratorsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
